import = [
  "~/.config/alacritty/themes/solarized_osaka.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 17.0


[font.normal]
family = "Fira Code Nerd Font Mono"
style = "Regular"


[font.bold]
style="Regular"


[window]
decorations = "Full" # Change to None if your feeling edgy
opacity = 0.95
dimensions = {columns = 90, lines = 25}
resize_increments = true
dynamic_padding = true
blur = true
[window.position]
x = 400
y = 200
[window.padding]
x = 5
y = 10

[cursor.style]
shape = "Block"
blinking = "Never"

[selection]
save_to_clipboard = true

[shell]
program = "tmux"

[scrolling]
history = 10000

[keyboard]
bindings = [{key = "Q", mods = "Control", action = "None"}]
