import = [
  # "~/.config/alacritty/gruvbox_medium_dark.toml"
  # "~/.config/alacritty/gruvbox_dark.toml"
  #  "~/.config/alacritty/solarized_light.toml"
  #  "~/.config/alacritty/everforest_dark.toml"
  # "~/.config/alacritty/remedy_dark.toml"
  "~/.config/alacritty/jonhoo.toml"
]

[font]
size = 14.0

[font.normal]
# family = "Hasklug Nerd Font Mono"
#family = "GeistMono NFM"
family = "Noto Sans Mono"
# family = "FantasqueSansM Nerd Font Mono"
style = "Regular"

[window]
decorations = "None"
opacity = 0.99
dimensions = {columns = 90, lines = 20}
resize_increments = true

[window.position]
x = 400
y = 200
[window.padding]
x = 5
y = 10

[cursor.style]
shape = "Underline"
blinking = "Never"

[selection]
save_to_clipboard = true

[shell]
program = "tmux"

[scrolling]
history = 10000
