import = [
  # "~/.config/alacritty/gruvbox_medium_dark.toml"
  # "~/.config/alacritty/gruvbox_dark.toml"
  # "~/.config/alacritty/solarized_light.toml"
  # "~/.config/alacritty/everforest_dark.toml"
  # "~/.config/alacritty/remedy_dark.toml"
  #   "~/.config/alacritty/jonhoo.toml"
  #  "~/.config/alacritty/citylights.toml"
  # "~/.config/alacritty/ayu-dark.toml"
  # "~/.config/alacritty/blood_moon.toml"
   "~/.config/alacritty/seashells.toml"

]

[font]
size = 15.0

[font.normal]
# family = "Hasklug Nerd Font Mono"
# family = "GeistMono NFM"
# family = "Noto Sans Mono"
family = "ZedMono Nerd Font"
# family = "FantasqueSansM Nerd Font Mono"
style = "Regular"

[window]
decorations = "Full" # Change to None if your feeling edgy
opacity = 1.0
dimensions = {columns = 90, lines = 25}
resize_increments = true
dynamic_padding = true
blur = true
[window.position]
x = 400
y = 200
[window.padding]
x = 5
y = 10

[cursor.style]
shape = "Underline"
blinking = "Never"

[selection]
save_to_clipboard = true

[shell]
program = "tmux"

[scrolling]
history = 10000

[keyboard]
bindings = [{key = "Q", mods = "Control", action = "None"}]
