import = [
  "~/.config/alacritty/themes/coolnight.toml",
]

[font]
size = 18.0


[font.normal]
# family = "Hasklug Nerd Font Mono"
# family = "GeistMono NF"
family = "Noto Sans Mono"
# family = "ZedMono Nerd Font"
# family = "FantasqueSansM Nerd Font Mono"
# family = "Perfect DOS VGA 437"
# family = "SF Mono"
# family = "Ubuntu Mono"
# family = "Google Sans Mono"
# family = "Gitlab Mono"
# family = "IBM PlexMono"
# family = "JetBrains Mono"
style = "Regular"


[font.bold]
style="Regular"


[window]
decorations = "Full" # Change to None if your feeling edgy
opacity = 0.95
dimensions = {columns = 90, lines = 25}
resize_increments = true
dynamic_padding = true
blur = true
[window.position]
x = 400
y = 200
[window.padding]
x = 5
y = 10

[cursor.style]
shape = "Block"
blinking = "Never"

[selection]
save_to_clipboard = true

[shell]
program = "tmux"

[scrolling]
history = 10000

[keyboard]
bindings = [{key = "Q", mods = "Control", action = "None"}]
