import = [
  #  "~/.config/alacritty/gruvbox_medium_dark.toml"
  # "~/.config/alacritty/gruvbox_dark.toml"
  #  "~/.config/alacritty/solarized_light.toml"
  "~/.config/alacritty/everforest_dark.toml"


]

[window]
decorations = "None"
opacity = 0.95
dimensions = {columns = 80, lines = 35}
[window.padding]
x = 10
y = 10

[font]
size = 16.0

[font.normal]
# family = "Hasklug Nerd Font Mono"
family = "GeistMono NFM"
# family = "FantasqueSansM Nerd Font Mono"
style = "Regular"

[cursor.style]
shape = "Underline"
blinking = "Never"

[selection]
save_to_clipboard = true

[shell]
program = "tmux"
