[font]
size = 11.0

[font.normal]
family = "Iosevka Term"
style = "Regular"

[window]
decorations = "None"
dimensions = {columns = 90, lines = 25}
resize_increments = true
dynamic_padding = true
blur = true

[window.position]
x = 400
y = 200
[window.padding]
x = 5
y = 10

[cursor.style]
shape = "Block"
blinking = "Never"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "tmux"

[scrolling]
history = 10000

[keyboard]
bindings = [{key = "Q", mods = "Control", action = "None"}]

[general]
import = [
  "~/.config/alacritty/themes/tokyo-night-storm.toml",
]
