import = [
  "~/.config/alacritty/themes/taerminal.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 15.0


[font.normal]
family = "D2CodingLigature Nerd Font Mono"
style = "Regular"

[window]
decorations = "Full"
opacity = 0.99
dimensions = {columns = 90, lines = 25}
resize_increments = true
dynamic_padding = true
blur = true
[window.position]
x = 400
y = 200
[window.padding]
x = 5
y = 10

[cursor.style]
shape = "Block"
blinking = "Never"

[selection]
save_to_clipboard = true

[shell]
program = "tmux"

[scrolling]
history = 10000

[keyboard]
bindings = [{key = "Q", mods = "Control", action = "None"}]
