[font]
size = 11.0

[font.offset]
y = 1
x = 1

[font.normal]
# family = "MesloLGL Nerd Font Mono"
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations = "None"
dimensions = {columns = 90, lines = 25}
resize_increments = true
dynamic_padding = true
opacity = 0.95
blur = true

[window.position]
x = 400
y = 200

[cursor.style]
shape = "Block"
blinking = "Never"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "tmux"

[scrolling]
history = 10000

[keyboard]
bindings = [{key = "Q", mods = "Control", action = "None"}]

[general]
import = [
  "~/.config/alacritty/themes/gruvbox_material_hard_dark.toml",
]
