background #17130D
foreground #BCB2A7
cursor #BCB2A7
cursor_text_color #17130D
selection_foreground #17130D
selection_background #BCB2A7
color0  #17130D
color1  #FB7279
color2  #79AD20
color3  #D88E20
color4  #5A9FFA
color5  #D576FA
color6  #23B0A5
color7  #BCB2A7
color8  #8E8274
color9  #EF9DA0
color10 #93C159
color11 #EAA559
color12 #95B4ED
color13 #D4A0ED
color14 #5FC3BA
color15 #FFFFFF
