background #14100e
foreground #ece0c6
cursor #ffc64d
cursor_text_color #14100e
selection_foreground #ece0c6
selection_background #3f342a
color0  #14100e
color1  #be7564
color2  #9bb079
color3  #ffc64d
color4  #d3a75f
color5  #c48374
color6  #a5b886
color7  #ece0c6
color8  #5a4f43
color9  #ca8e80
color10 #adbe91
color11 #f0dec0
color12 #dab477
color13 #d09c8f
color14 #b7c69e
color15 #ede2c9
