# tokyodark — derived from tiagovla/tokyodark.nvim main palette
# (lua/tokyodark/palettes/tokyodark.lua).

foreground            #a0a8cd
background            #11121d

cursor                #a0a8cd
cursor_text_color     #11121d

selection_foreground  #a0a8cd
selection_background  #353945

# Normal
color0  #06080a
color1  #ee6d85
color2  #76c8c8
color3  #ffd9a9
color4  #7199ee
color5  #a485dd
color6  #38a89d
color7  #a0a8cd

# Bright
color8  #4a5057
color9  #f65b5b
color10 #76c8c8
color11 #ffaa70
color12 #76cce0
color13 #a485dd
color14 #76cce0
color15 #ffffff

url_color #7199ee

active_border_color   #a485dd
inactive_border_color #4a5057

active_tab_foreground   #11121d
active_tab_background   #a485dd
inactive_tab_foreground #7e8294
inactive_tab_background #1a1b2a
