# vim:ft=kitty

## name: TokyoDark
## description: A dark, clean, and elegant theme based on TokyoDark.

# Basic Colors
background              #11121D
foreground              #A0A8CD
selection_background    #353945
selection_foreground    #A0A8CD

# Cursor Colors
cursor                  #A0A8CD
cursor_text_color       #11121D

# URL Underline
url_color               #7199EE

# Tab Bar
active_tab_foreground   #11121D
active_tab_background   #7199EE
inactive_tab_foreground #A0A8CD
inactive_tab_background #1A1B2A
tab_bar_background      #06080A

# Window Borders
active_border_color     #7199EE
inactive_border_color   #212234

# ---- The 16 Terminal Colors ----

# Black
color0  #1A1B2A
color8  #4A5057

# Red
color1  #EE6D85
color9  #FE6D85

# Green
color2  #95C561
color10 #98C379

# Yellow
color3  #D7A65F
color11 #F6955B

# Blue
color4  #7199EE
color12 #9FBBF3

# Magenta / Purple
color5  #A485DD
color13 #A485DD

# Cyan
color6  #38A89D
color14 #38A89D

# White
color7  #A0A8CD
color15 #A0A8CD
