background #050807
foreground #f5fbf6
cursor #1ce8e8
cursor_text_color #050807
selection_foreground #f5fbf6
selection_background #0e2018
color0  #050807
color1  #e8ff00
color2  #a3ff5a
color3  #e8ff00
color4  #1ce8e8
color5  #33ffb0
color6  #8eff6a
color7  #f5fbf6
color8  #4a665a
color9  #f4ff66
color10 #c0ff85
color11 #f4ff66
color12 #66f0f0
color13 #66ffc8
color14 #b0ff8e
color15 #ffffff
