background #070510
foreground #f5f0fb
cursor #d76aff
cursor_text_color #070510
selection_foreground #f5f0fb
selection_background #1f1438
color0  #070510
color1  #ff6aff
color2  #d76aff
color3  #ffd84d
color4  #5ad7ff
color5  #d76aff
color6  #5ad7ff
color7  #f5f0fb
color8  #5a4e7a
color9  #ff9aff
color10 #e69aff
color11 #ffe680
color12 #8ce4ff
color13 #e69aff
color14 #8ce4ff
color15 #ffffff
