background #0a0604
foreground #fbf5ee
cursor #ffd84d
cursor_text_color #0a0604
selection_foreground #fbf5ee
selection_background #2a160a
color0  #0a0604
color1  #ff3a3a
color2  #ff9a33
color3  #ffd84d
color4  #ff5aa3
color5  #ffb86a
color6  #ffd84d
color7  #fbf5ee
color8  #6b5544
color9  #ff6e6e
color10 #ffb866
color11 #ffe680
color12 #ff85bd
color13 #ffd09a
color14 #ffe680
color15 #ffffff
