# VSCode Dark — Mofiqul/vscode.nvim
# https://github.com/Mofiqul/vscode.nvim

background              #1F1F1F
foreground              #D4D4D4
selection_background    #264F78
selection_foreground    #D4D4D4

cursor                  #AEAFAD
cursor_text_color       #1F1F1F

url_color               #569CD6
active_border_color     #569CD6
inactive_border_color   #444444

active_tab_background    #1F1F1F
active_tab_foreground    #D4D4D4
inactive_tab_background  #2D2D2D
inactive_tab_foreground  #808080

# black
color0  #1F1F1F
color8  #808080
# red
color1  #F44747
color9  #F44747
# green
color2  #6A9955
color10 #6A9955
# yellow
color3  #DCDCAA
color11 #DCDCAA
# blue
color4  #569CD6
color12 #569CD6
# magenta
color5  #C586C0
color13 #C586C0
# cyan
color6  #4EC9B0
color14 #4EC9B0
# white
color7  #D4D4D4
color15 #D4D4D4
