-- Colorscheme → Kitty + Ghostty + WezTerm sync.
--
-- On every `:colorscheme <name>`:
--   1. The matching kitty palette file (from `sources` below, or any `.conf`
--      in ~/.config/kitty/<name>.conf) is copied to current-theme.conf as a
--      baseline.
--   2. nvim's runtime Normal/Cursor/Visual highlights and any
--      `vim.g.terminal_color_0..15` are overlaid onto that file — so kitty's
--      background/foreground/cursor/selection (and ANSI, when the theme sets
--      it) mirror EXACTLY what the active colorscheme renders inside nvim.
--      This catches themes that ship no kitty extras (yorumi) or themes whose
--      bundled extras drift from the live highlights.
--   3. `kitty @ set-colors` pushes the patched file live.
--   4. The patched palette is parsed and translated into the Ghostty +
--      WezTerm config files.
--
-- Requires in kitty.conf: `allow_remote_control yes` and
-- `include current-theme.conf` inside the BEGIN_KITTY_THEME block.

local M = {}

-- Explicit colorscheme → kitty .conf source map. Anything not listed falls
-- back to ~/.config/kitty/<name>.conf if that file exists (this is how
-- gruvbox-material is wired — see ~/.config/kitty/gruvbox-material.conf).
local sources = {
	crucible = function()
		local ok, cfg = pcall(require, "crucible.config")
		local variant = (ok and cfg.options and cfg.options.variant) or "crucible"
		return vim.fn.stdpath("data") .. "/lazy/crucible.nvim/extras/kitty/" .. variant .. ".conf"
	end,
}

local function resolve_source(name)
	local source = sources[name]
	if type(source) == "function" then
		source = source()
	end
	if source and vim.fn.filereadable(source) == 1 then
		return source
	end
	-- Fallback: ~/.config/kitty/<name>.conf
	local guess = vim.fn.expand("~/.config/kitty/" .. name .. ".conf")
	if vim.fn.filereadable(guess) == 1 then
		return guess
	end
	return nil
end

-- Recursively parse a kitty .conf, following `include` directives, into a
-- flat key→value map (e.g. foreground=#cdcdcd, color0=#252530).
local function parse_kitty_conf(path, seen)
	seen = seen or {}
	local map = {}
	if not path or vim.fn.filereadable(path) == 0 or seen[path] then
		return map
	end
	seen[path] = true
	for line in io.lines(path) do
		line = line:gsub("^%s+", ""):gsub("%s+$", "")
		if #line > 0 and line:sub(1, 1) ~= "#" then
			local inc = line:match("^include%s+(.+)$")
			if inc then
				if inc:sub(1, 1) ~= "/" then
					inc = vim.fn.fnamemodify(path, ":h") .. "/" .. inc
				end
				for k, v in pairs(parse_kitty_conf(inc, seen)) do
					map[k] = v
				end
			else
				local key, val = line:match("^(%S+)%s+(%S+)")
				if key and val then
					map[key] = val
				end
			end
		end
	end
	return map
end

local function write_file(path, body)
	vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
	local f = io.open(path, "w")
	if not f then
		return false
	end
	f:write(body)
	f:close()
	return true
end

local function write_ghostty(colors, scheme)
	local lines = {
		"# Auto-generated by nvim terminal-sync.lua — do not edit by hand.",
		"# Active: " .. (scheme or "?"),
	}
	local map = {
		foreground = "foreground",
		background = "background",
		cursor = "cursor-color",
		cursor_text_color = "cursor-text",
		selection_foreground = "selection-foreground",
		selection_background = "selection-background",
	}
	for src, dst in pairs(map) do
		local v = colors[src]
		if v and v:lower() ~= "none" then
			table.insert(lines, dst .. " = " .. v)
		end
	end
	for i = 0, 15 do
		local c = colors["color" .. i]
		if c then
			table.insert(lines, "palette = " .. i .. "=" .. c)
		end
	end
	write_file(vim.fn.expand("~/.config/ghostty/current-theme"), table.concat(lines, "\n") .. "\n")
	-- Ghostty reload disabled — reload manually after changes.
end

local function write_wezterm(colors, scheme)
	local function q(c)
		return c and ("'" .. c .. "'") or "nil"
	end
	local ansi, brights = {}, {}
	for i = 0, 7 do
		table.insert(ansi, q(colors["color" .. i]))
	end
	for i = 8, 15 do
		table.insert(brights, q(colors["color" .. i]))
	end
	local body = string.format(
		[[-- Auto-generated by nvim terminal-sync.lua -- do not edit by hand.
-- Active: %s
return {
  foreground = %s,
  background = %s,
  cursor_bg = %s,
  cursor_fg = %s,
  cursor_border = %s,
  selection_fg = %s,
  selection_bg = %s,
  ansi = { %s },
  brights = { %s },
}
]],
		scheme or "?",
		q(colors.foreground),
		q(colors.background),
		q(colors.cursor),
		q(colors.cursor_text_color or colors.background),
		q(colors.cursor),
		q(colors.selection_foreground),
		q(colors.selection_background),
		table.concat(ansi, ", "),
		table.concat(brights, ", ")
	)
	-- WezTerm auto-reloads on file change.
	write_file(vim.fn.expand("~/.config/wezterm/current-theme.lua"), body)
end

-- Convert nvim_get_hl numeric color to "#rrggbb".
local function hex(rgb)
	if type(rgb) ~= "number" then
		return nil
	end
	return string.format("#%06x", rgb)
end

-- Pull the values kitty cares about from the live colorscheme.
-- Returns a map keyed by kitty conf keys (foreground/background/cursor/
-- cursor_text_color/selection_foreground/selection_background/color0..15).
-- ANSI keys are only set if the colorscheme exported `vim.g.terminal_color_*`.
local function read_runtime_colors()
	local function get_hl(name)
		local ok, h = pcall(vim.api.nvim_get_hl, 0, { name = name, link = false })
		return (ok and h) or {}
	end
	local normal = get_hl("Normal")
	local cursor = get_hl("Cursor")
	local visual = get_hl("Visual")
	local out = {
		foreground = hex(normal.fg),
		background = hex(normal.bg),
		cursor = hex(cursor.bg) or hex(normal.fg),
		cursor_text_color = hex(cursor.fg) or hex(normal.bg),
		selection_foreground = hex(visual.fg) or hex(normal.fg),
		selection_background = hex(visual.bg),
	}
	for i = 0, 15 do
		local v = vim.g["terminal_color_" .. i]
		if type(v) == "string" and v:match("^#%x%x%x%x%x%x$") then
			out["color" .. i] = v
		end
	end
	return out
end

-- In-place patch: for each key in `overrides` with a non-nil value, replace
-- the first matching `key  value` line in the kitty conf, or append it.
local function patch_kitty_conf(path, overrides)
	local f = io.open(path, "r")
	if not f then
		return
	end
	local body = f:read("*a")
	f:close()
	if not body:match("\n$") then
		body = body .. "\n"
	end
	for key, val in pairs(overrides) do
		if val then
			local esc = key:gsub("([%-%.%+%[%]%(%)%$%^%%%?%*])", "%%%1")
			local replaced
			body, replaced = body:gsub("(\n" .. esc .. "%s+)[^\n]+", "%1" .. val, 1)
			if replaced == 0 then
				body, replaced = body:gsub("^(" .. esc .. "%s+)[^\n]+", "%1" .. val, 1)
			end
			if replaced == 0 then
				body = body .. key .. " " .. val .. "\n"
			end
		end
	end
	local out = io.open(path, "w")
	if out then
		out:write(body)
		out:close()
	end
end

local function sync(name)
	local source = resolve_source(name)
	if not source then
		return
	end
	-- Stage 1 (sync, before highlights are guaranteed applied):
	-- copy the static baseline so we don't lose ANSI for themes that don't
	-- export terminal_color_*.
	local target = vim.fn.expand("~/.config/kitty/current-theme.conf")
	vim.fn.system({ "cp", source, target })
	-- Stage 2 (deferred until the colorscheme has finished applying):
	-- overlay nvim's live highlights, push to kitty, and regenerate the
	-- ghostty/wezterm files from the patched palette.
	vim.schedule(function()
		patch_kitty_conf(target, read_runtime_colors())
		vim.fn.jobstart({ "kitty", "@", "set-colors", "-c", target }, { detach = true })
		local colors = parse_kitty_conf(target)
		write_ghostty(colors, name)
		write_wezterm(colors, name)
	end)
end

M.sync = sync

vim.api.nvim_create_autocmd("ColorScheme", {
	group = vim.api.nvim_create_augroup("TerminalColorschemeSync", { clear = true }),
	callback = function(args)
		sync(args.match)
	end,
})

return M
