-- Colorscheme → Kitty + Ghostty + WezTerm sync.
--
-- On every `:colorscheme <name>`:
--   1. The matching kitty palette file (from `sources` below, or any `.conf`
--      in ~/.config/kitty/<name>.conf) is copied to current-theme.conf and
--      pushed live via `kitty @ set-colors`.
--   2. The palette is parsed into a flat color map and translated into
--      ~/.config/ghostty/current-theme + ~/.config/wezterm/current-theme.lua.
--   3. Ghostty is signalled (SIGUSR2 → config reload). WezTerm auto-reloads.
--
-- Requires in kitty.conf: `allow_remote_control yes` and
-- `include current-theme.conf` inside the BEGIN_KITTY_THEME block.

local M = {}

-- Explicit colorscheme → kitty .conf source map. Anything not listed falls
-- back to ~/.config/kitty/<name>.conf if that file exists (this is how
-- gruvbox-material is wired — see ~/.config/kitty/gruvbox-material.conf).
local sources = {
	crucible = function()
		local ok, cfg = pcall(require, "crucible.config")
		local variant = (ok and cfg.options and cfg.options.variant) or "crucible"
		return vim.fn.stdpath("data") .. "/lazy/crucible.nvim/extras/kitty/" .. variant .. ".conf"
	end,
}

local function resolve_source(name)
	local source = sources[name]
	if type(source) == "function" then
		source = source()
	end
	if source and vim.fn.filereadable(source) == 1 then
		return source
	end
	-- Fallback: ~/.config/kitty/<name>.conf
	local guess = vim.fn.expand("~/.config/kitty/" .. name .. ".conf")
	if vim.fn.filereadable(guess) == 1 then
		return guess
	end
	return nil
end

-- Recursively parse a kitty .conf, following `include` directives, into a
-- flat key→value map (e.g. foreground=#cdcdcd, color0=#252530).
local function parse_kitty_conf(path, seen)
	seen = seen or {}
	local map = {}
	if not path or vim.fn.filereadable(path) == 0 or seen[path] then
		return map
	end
	seen[path] = true
	for line in io.lines(path) do
		line = line:gsub("^%s+", ""):gsub("%s+$", "")
		if #line > 0 and line:sub(1, 1) ~= "#" then
			local inc = line:match("^include%s+(.+)$")
			if inc then
				if inc:sub(1, 1) ~= "/" then
					inc = vim.fn.fnamemodify(path, ":h") .. "/" .. inc
				end
				for k, v in pairs(parse_kitty_conf(inc, seen)) do
					map[k] = v
				end
			else
				local key, val = line:match("^(%S+)%s+(%S+)")
				if key and val then
					map[key] = val
				end
			end
		end
	end
	return map
end

local function write_file(path, body)
	vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
	local f = io.open(path, "w")
	if not f then
		return false
	end
	f:write(body)
	f:close()
	return true
end

local function write_ghostty(colors, scheme)
	local lines = {
		"# Auto-generated by nvim terminal-sync.lua — do not edit by hand.",
		"# Active: " .. (scheme or "?"),
	}
	local map = {
		foreground = "foreground",
		background = "background",
		cursor = "cursor-color",
		cursor_text_color = "cursor-text",
		selection_foreground = "selection-foreground",
		selection_background = "selection-background",
	}
	for src, dst in pairs(map) do
		local v = colors[src]
		if v and v:lower() ~= "none" then
			table.insert(lines, dst .. " = " .. v)
		end
	end
	for i = 0, 15 do
		local c = colors["color" .. i]
		if c then
			table.insert(lines, "palette = " .. i .. "=" .. c)
		end
	end
	write_file(vim.fn.expand("~/.config/ghostty/current-theme"), table.concat(lines, "\n") .. "\n")
	-- Ghostty reload disabled — reload manually after changes.
end

local function write_wezterm(colors, scheme)
	local function q(c)
		return c and ("'" .. c .. "'") or "nil"
	end
	local ansi, brights = {}, {}
	for i = 0, 7 do
		table.insert(ansi, q(colors["color" .. i]))
	end
	for i = 8, 15 do
		table.insert(brights, q(colors["color" .. i]))
	end
	local body = string.format(
		[[-- Auto-generated by nvim terminal-sync.lua -- do not edit by hand.
-- Active: %s
return {
  foreground = %s,
  background = %s,
  cursor_bg = %s,
  cursor_fg = %s,
  cursor_border = %s,
  selection_fg = %s,
  selection_bg = %s,
  ansi = { %s },
  brights = { %s },
}
]],
		scheme or "?",
		q(colors.foreground),
		q(colors.background),
		q(colors.cursor),
		q(colors.cursor_text_color or colors.background),
		q(colors.cursor),
		q(colors.selection_foreground),
		q(colors.selection_background),
		table.concat(ansi, ", "),
		table.concat(brights, ", ")
	)
	-- WezTerm auto-reloads on file change.
	write_file(vim.fn.expand("~/.config/wezterm/current-theme.lua"), body)
end

local function sync(name)
	local source = resolve_source(name)
	if not source then
		return
	end
	-- Kitty.
	local target = vim.fn.expand("~/.config/kitty/current-theme.conf")
	vim.fn.system({ "cp", source, target })
	vim.fn.jobstart({ "kitty", "@", "set-colors", "-c", target }, { detach = true })
	-- Ghostty + WezTerm derived from the same palette.
	local colors = parse_kitty_conf(source)
	write_ghostty(colors, name)
	write_wezterm(colors, name)
end

M.sync = sync

vim.api.nvim_create_autocmd("ColorScheme", {
	group = vim.api.nvim_create_augroup("TerminalColorschemeSync", { clear = true }),
	callback = function(args)
		sync(args.match)
	end,
})

return M
