-- gruvbox-ish — port of the Zed "Gruvbox ish Dark Hard" theme
-- (https://github.com/tristan-f-r/zed-gruvbox-ish, themes/gruvbox-ish.json) to a
-- standalone nvim colorscheme. Warm gruvbox: cream fg #dfbf8e on dark0_hard
-- #1d2021, red keywords, green strings, purple numbers/constants, yellow types,
-- orange constructors/tags, light-aqua functions, aqua UI accent.
--
-- Standalone — no plugin dependency. Auto-discovered via colors/gruvbox-ish.lua;
-- activate with `:colorscheme gruvbox-ish`. Kitty palette mirror:
-- ~/.config/kitty/gruvbox-ish.conf (resolved by terminal-sync.lua via the name).
-- lua/config/plugins/lualine.lua swaps to gruvbox-ish-lualine on ColorScheme.
-- `Normal.bg = NONE` so the kitty gruvbox-blur wallpaper shows through.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.background = "dark"
vim.g.colors_name = "gruvbox-ish"

local p = {
  -- structural ramp (dark0_hard base)
  bg = "#1d2021", bg1 = "#282828", bg2 = "#32302f", bg3 = "#3c3836", bg4 = "#504945",
  sel = "#504945",
  fg = "#dfbf8e", fg_dim = "#a89984", comment = "#928374", dim = "#7c6f64", linenr = "#3c3836",
  -- accents (from the gruvbox-ish syntax + ansi)
  red = "#d75f5f", green = "#8b9553", yellow = "#d69617", blue = "#458588",
  purple = "#d3869b", aqua = "#689d6a", orange = "#e78a4e", func = "#87af87",
  attr = "#cea64a", blue_lt = "#83a598", magenta = "#b16286",
  accent = "#689d6a", -- aqua: primary UI accent
  -- diff / git
  add = "#8b9553", add_bg = "#2a2e1f",
  del = "#d75f5f", del_bg = "#3a2422",
  chg = "#83a598", chg_bg = "#26302f", chg_txt_bg = "#36403f",
  -- diagnostics
  err = "#d75f5f", warn = "#d69617", info = "#458588", hint = "#83a598", ok = "#8b9553",
  none = "NONE",
}

local groups = {
  -- editor UI
  Normal = { fg = p.fg, bg = p.none },
  NormalNC = { fg = p.fg, bg = p.none },
  NormalFloat = { fg = p.fg, bg = p.bg1 },
  FloatBorder = { fg = p.bg4, bg = p.bg1 },
  FloatTitle = { fg = p.accent, bg = p.bg1, bold = true },
  ColorColumn = { bg = p.bg1 },
  Conceal = { fg = p.fg_dim },
  Cursor = { fg = p.bg, bg = p.fg },
  lCursor = { fg = p.bg, bg = p.fg },
  CursorIM = { fg = p.bg, bg = p.fg },
  TermCursor = { fg = p.bg, bg = p.fg },
  CursorColumn = { bg = p.bg1 },
  CursorLine = { bg = p.none },
  Directory = { fg = p.accent },
  EndOfBuffer = { fg = p.bg2 },
  ErrorMsg = { fg = p.err },
  WinSeparator = { fg = p.bg4, bg = p.none },
  VertSplit = { fg = p.bg4, bg = p.none },
  Folded = { fg = p.fg_dim, bg = p.bg1 },
  FoldColumn = { fg = p.dim, bg = p.none },
  SignColumn = { fg = p.fg_dim, bg = p.none },
  IncSearch = { fg = p.bg, bg = p.orange },
  CurSearch = { fg = p.bg, bg = p.orange },
  Substitute = { fg = p.bg, bg = p.red },
  LineNr = { fg = p.linenr },
  LineNrAbove = { fg = p.linenr },
  LineNrBelow = { fg = p.linenr },
  CursorLineNr = { fg = p.yellow, bold = true },
  MatchParen = { fg = p.fg, bg = p.bg4, bold = true },
  ModeMsg = { fg = p.fg },
  MsgArea = { fg = p.fg },
  MoreMsg = { fg = p.accent },
  NonText = { fg = p.bg4 },
  Pmenu = { fg = p.fg, bg = p.bg2 },
  PmenuSel = { fg = p.fg, bg = p.sel },
  PmenuKind = { fg = p.accent, bg = p.bg2 },
  PmenuKindSel = { fg = p.accent, bg = p.sel },
  PmenuExtra = { fg = p.fg_dim, bg = p.bg2 },
  PmenuExtraSel = { fg = p.fg, bg = p.sel },
  PmenuSbar = { bg = p.bg3 },
  PmenuThumb = { bg = p.bg4 },
  Question = { fg = p.accent },
  QuickFixLine = { bg = p.bg2, bold = true },
  Search = { fg = p.bg, bg = p.yellow },
  SpecialKey = { fg = p.bg4 },
  SpellBad = { undercurl = true, sp = p.err },
  SpellCap = { undercurl = true, sp = p.warn },
  SpellLocal = { undercurl = true, sp = p.info },
  SpellRare = { undercurl = true, sp = p.hint },
  StatusLine = { fg = p.fg, bg = p.bg2 },
  StatusLineNC = { fg = p.fg_dim, bg = p.bg1 },
  TabLine = { fg = p.fg_dim, bg = p.bg1 },
  TabLineFill = { bg = p.bg },
  TabLineSel = { fg = p.fg, bg = p.sel },
  Title = { fg = p.green, bold = true },
  Visual = { bg = p.sel },
  VisualNOS = { bg = p.sel },
  WarningMsg = { fg = p.warn },
  Whitespace = { fg = p.bg4 },
  WildMenu = { fg = p.bg, bg = p.accent },
  WinBar = { fg = p.fg, bg = p.none },
  WinBarNC = { fg = p.fg_dim, bg = p.none },

  -- legacy syntax
  Comment = { fg = p.comment, italic = true },
  Constant = { fg = p.purple },
  String = { fg = p.green },
  Character = { fg = p.green },
  Number = { fg = p.purple },
  Boolean = { fg = p.purple },
  Float = { fg = p.purple },
  Identifier = { fg = p.fg },
  Function = { fg = p.func },
  Statement = { fg = p.red },
  Conditional = { fg = p.red },
  Repeat = { fg = p.red },
  Label = { fg = p.red },
  Operator = { fg = p.fg },
  Keyword = { fg = p.red },
  Exception = { fg = p.red },
  PreProc = { fg = p.orange },
  Include = { fg = p.orange },
  Define = { fg = p.orange },
  Macro = { fg = p.orange },
  PreCondit = { fg = p.orange },
  Type = { fg = p.yellow },
  StorageClass = { fg = p.yellow },
  Structure = { fg = p.yellow },
  Typedef = { fg = p.yellow },
  Special = { fg = p.orange },
  SpecialChar = { fg = p.orange },
  Tag = { fg = p.orange },
  Delimiter = { fg = p.fg },
  SpecialComment = { fg = p.fg_dim },
  Debug = { fg = p.red },
  Underlined = { fg = p.accent, underline = true },
  Ignore = { fg = p.dim },
  Error = { fg = p.err },
  Todo = { fg = p.bg, bg = p.yellow, bold = true },

  -- diff (builtin + diff syntax)
  DiffAdd = { bg = p.add_bg },
  DiffChange = { bg = p.chg_bg },
  DiffDelete = { fg = p.del, bg = p.del_bg },
  DiffText = { fg = p.fg, bg = p.chg_txt_bg },
  diffAdded = { fg = p.add },
  diffRemoved = { fg = p.del },
  diffChanged = { fg = p.chg },
  diffLine = { fg = p.accent },
  diffFile = { fg = p.yellow },
  diffNewFile = { fg = p.add },
  diffOldFile = { fg = p.del },
  diffIndexLine = { fg = p.fg_dim },
  Added = { fg = p.add },
  Removed = { fg = p.del },
  Changed = { fg = p.chg },

  -- diagnostics
  DiagnosticError = { fg = p.err },
  DiagnosticWarn = { fg = p.warn },
  DiagnosticInfo = { fg = p.info },
  DiagnosticHint = { fg = p.hint },
  DiagnosticOk = { fg = p.ok },
  DiagnosticUnderlineError = { undercurl = true, sp = p.err },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.warn },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.info },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.hint },
  DiagnosticUnderlineOk = { undercurl = true, sp = p.ok },
  DiagnosticVirtualTextError = { fg = p.err, bg = p.del_bg },
  DiagnosticVirtualTextWarn = { fg = p.warn, bg = p.bg1 },
  DiagnosticVirtualTextInfo = { fg = p.info, bg = p.bg1 },
  DiagnosticVirtualTextHint = { fg = p.hint, bg = p.bg1 },

  -- LSP references / inlay
  LspReferenceText = { bg = p.bg3 },
  LspReferenceRead = { bg = p.bg3 },
  LspReferenceWrite = { bg = p.bg3 },
  LspInlayHint = { fg = p.comment, bg = p.bg1 },
  LspCodeLens = { fg = p.comment },
  LspSignatureActiveParameter = { fg = p.accent, bold = true },

  -- treesitter
  ["@comment"] = { link = "Comment" },
  ["@comment.error"] = { fg = p.err },
  ["@comment.warning"] = { fg = p.warn },
  ["@comment.todo"] = { link = "Todo" },
  ["@comment.note"] = { fg = p.info },
  ["@keyword"] = { fg = p.red },
  ["@keyword.function"] = { fg = p.red },
  ["@keyword.return"] = { fg = p.red },
  ["@keyword.operator"] = { fg = p.red },
  ["@keyword.conditional"] = { fg = p.red },
  ["@keyword.repeat"] = { fg = p.red },
  ["@keyword.import"] = { fg = p.red },
  ["@keyword.exception"] = { fg = p.red },
  ["@keyword.directive"] = { fg = p.orange },
  ["@conditional"] = { fg = p.red },
  ["@repeat"] = { fg = p.red },
  ["@exception"] = { fg = p.red },
  ["@include"] = { fg = p.orange },
  ["@type"] = { fg = p.yellow },
  ["@type.builtin"] = { fg = p.yellow },
  ["@type.definition"] = { fg = p.yellow },
  ["@type.qualifier"] = { fg = p.red },
  ["@namespace"] = { fg = p.yellow },
  ["@module"] = { fg = p.yellow },
  ["@function"] = { fg = p.func },
  ["@function.builtin"] = { fg = p.func },
  ["@function.call"] = { fg = p.func },
  ["@function.macro"] = { fg = p.orange },
  ["@method"] = { fg = p.func },
  ["@method.call"] = { fg = p.func },
  ["@constructor"] = { fg = p.orange },
  ["@variable"] = { fg = p.fg },
  ["@variable.builtin"] = { fg = p.purple },
  ["@variable.parameter"] = { fg = p.fg },
  ["@variable.member"] = { fg = p.aqua },
  ["@parameter"] = { fg = p.fg },
  ["@field"] = { fg = p.aqua },
  ["@property"] = { fg = p.aqua },
  ["@constant"] = { fg = p.purple },
  ["@constant.builtin"] = { fg = p.purple },
  ["@constant.macro"] = { fg = p.orange },
  ["@string"] = { fg = p.green },
  ["@string.regex"] = { fg = p.green },
  ["@string.escape"] = { fg = p.red },
  ["@string.special"] = { fg = p.green },
  ["@character"] = { fg = p.green },
  ["@character.special"] = { fg = p.orange },
  ["@number"] = { fg = p.purple },
  ["@boolean"] = { fg = p.purple },
  ["@float"] = { fg = p.purple },
  ["@operator"] = { fg = p.fg },
  ["@punctuation.delimiter"] = { fg = p.fg },
  ["@punctuation.bracket"] = { fg = p.fg },
  ["@punctuation.special"] = { fg = p.orange },
  ["@tag"] = { fg = p.orange },
  ["@tag.attribute"] = { fg = p.attr },
  ["@tag.delimiter"] = { fg = p.fg },
  ["@label"] = { fg = p.red },
  ["@annotation"] = { fg = p.attr },
  ["@attribute"] = { fg = p.attr },
  ["@markup.heading"] = { fg = p.green, bold = true },
  ["@markup.heading.1"] = { fg = p.green, bold = true },
  ["@markup.heading.2"] = { fg = p.aqua, bold = true },
  ["@markup.heading.3"] = { fg = p.yellow, bold = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.link"] = { fg = p.blue, underline = true },
  ["@markup.link.url"] = { fg = p.blue_lt, underline = true },
  ["@markup.raw"] = { fg = p.green },
  ["@markup.list"] = { fg = p.red },
  ["@markup.quote"] = { fg = p.fg_dim, italic = true },
  ["@diff.plus"] = { fg = p.add },
  ["@diff.minus"] = { fg = p.del },
  ["@diff.delta"] = { fg = p.chg },

  -- LSP semantic tokens
  ["@lsp.type.class"] = { link = "@type" },
  ["@lsp.type.decorator"] = { fg = p.attr },
  ["@lsp.type.enum"] = { link = "@type" },
  ["@lsp.type.enumMember"] = { fg = p.purple },
  ["@lsp.type.function"] = { link = "@function" },
  ["@lsp.type.interface"] = { link = "@type" },
  ["@lsp.type.macro"] = { fg = p.orange },
  ["@lsp.type.method"] = { link = "@function" },
  ["@lsp.type.namespace"] = { link = "@namespace" },
  ["@lsp.type.parameter"] = { fg = p.fg },
  ["@lsp.type.property"] = { fg = p.aqua },
  ["@lsp.type.struct"] = { link = "@type" },
  ["@lsp.type.type"] = { link = "@type" },
  ["@lsp.type.variable"] = { link = "@variable" },
  ["@lsp.type.keyword"] = { fg = p.red },

  -- gitsigns
  GitSignsAdd = { fg = p.add },
  GitSignsChange = { fg = p.chg },
  GitSignsDelete = { fg = p.del },
  GitSignsAddNr = { fg = p.add },
  GitSignsChangeNr = { fg = p.chg },
  GitSignsDeleteNr = { fg = p.del },
  GitSignsAddLn = { bg = p.add_bg },
  GitSignsChangeLn = { bg = p.chg_bg },
  GitSignsDeleteLn = { bg = p.del_bg },
  GitSignsCurrentLineBlame = { fg = p.comment, italic = true },

  -- blink.cmp
  BlinkCmpMenu = { fg = p.fg, bg = p.bg2 },
  BlinkCmpMenuBorder = { fg = p.bg4, bg = p.bg2 },
  BlinkCmpMenuSelection = { fg = p.fg, bg = p.sel },
  BlinkCmpScrollBarThumb = { bg = p.bg4 },
  BlinkCmpScrollBarGutter = { bg = p.bg3 },
  BlinkCmpLabel = { fg = p.fg },
  BlinkCmpLabelDeprecated = { fg = p.comment, strikethrough = true },
  BlinkCmpLabelMatch = { fg = p.accent, bold = true },
  BlinkCmpKind = { fg = p.accent },
  BlinkCmpDoc = { fg = p.fg, bg = p.bg1 },
  BlinkCmpDocBorder = { fg = p.bg4, bg = p.bg1 },
  BlinkCmpDocSeparator = { fg = p.bg4 },
  BlinkCmpSignatureHelp = { fg = p.fg, bg = p.bg1 },
  BlinkCmpSignatureHelpBorder = { fg = p.bg4, bg = p.bg1 },
  BlinkCmpGhostText = { fg = p.comment, italic = true },

  -- telescope
  TelescopeNormal = { fg = p.fg, bg = p.bg1 },
  TelescopeBorder = { fg = p.bg4, bg = p.bg1 },
  TelescopePromptNormal = { fg = p.fg, bg = p.bg2 },
  TelescopePromptBorder = { fg = p.bg4, bg = p.bg2 },
  TelescopePromptTitle = { fg = p.bg, bg = p.accent, bold = true },
  TelescopeResultsTitle = { fg = p.bg, bg = p.accent, bold = true },
  TelescopePreviewTitle = { fg = p.bg, bg = p.green, bold = true },
  TelescopePromptPrefix = { fg = p.accent },
  TelescopeSelection = { fg = p.fg, bg = p.sel },
  TelescopeSelectionCaret = { fg = p.accent, bg = p.sel },
  TelescopeMatching = { fg = p.accent, bold = true },
  TelescopeMultiSelection = { fg = p.orange },

  -- neo-tree
  NeoTreeNormal = { fg = p.fg, bg = p.none },
  NeoTreeNormalNC = { fg = p.fg, bg = p.none },
  NeoTreeDirectoryName = { fg = p.fg },
  NeoTreeDirectoryIcon = { fg = p.accent },
  NeoTreeRootName = { fg = p.accent, bold = true },
  NeoTreeFileName = { fg = p.fg },
  NeoTreeGitAdded = { fg = p.add },
  NeoTreeGitModified = { fg = p.chg },
  NeoTreeGitDeleted = { fg = p.del },
  NeoTreeGitUntracked = { fg = p.orange },
  NeoTreeIndentMarker = { fg = p.bg4 },
  NeoTreeExpander = { fg = p.fg_dim },

  -- bufferline (key groups; rest derives)
  BufferLineFill = { bg = p.bg },
  BufferLineBackground = { fg = p.fg_dim, bg = p.bg1 },
  BufferLineBufferVisible = { fg = p.fg_dim, bg = p.bg1 },
  BufferLineBufferSelected = { fg = p.fg, bg = p.none, bold = true },
  BufferLineSeparator = { fg = p.bg, bg = p.bg1 },
  BufferLineSeparatorVisible = { fg = p.bg, bg = p.bg1 },
  BufferLineSeparatorSelected = { fg = p.bg, bg = p.none },
  BufferLineIndicatorSelected = { fg = p.accent, bg = p.none },
  BufferLineModified = { fg = p.add, bg = p.bg1 },
  BufferLineModifiedSelected = { fg = p.add, bg = p.none },
  BufferLineModifiedVisible = { fg = p.add, bg = p.bg1 },

  -- which-key
  WhichKey = { fg = p.accent },
  WhichKeyGroup = { fg = p.yellow },
  WhichKeyDesc = { fg = p.fg },
  WhichKeySeparator = { fg = p.fg_dim },
  WhichKeyFloat = { bg = p.bg1 },
  WhichKeyBorder = { fg = p.bg4, bg = p.bg1 },
  WhichKeyValue = { fg = p.fg_dim },

  -- indent guides (ibl + snacks)
  IblIndent = { fg = p.bg2 },
  IblScope = { fg = p.bg4 },
  SnacksIndent = { fg = p.bg2 },
  SnacksIndentScope = { fg = p.bg4 },
}

for group, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, group, spec)
end
