-- vanta — standalone monochrome (grey + black + white) colorscheme with a neon
-- turquoise accent and red/green diff signals, transparent over the kitty
-- circuit/blueprint wallpaper.
--
-- Built from the gruvbox-vantablack iteration but DOES NOT depend on
-- gruvbox.nvim. Auto-discovered as a colorscheme via this file's location
-- (~/.config/nvim/colors/vanta.lua); activate with `:colorscheme vanta`.
-- Kitty palette mirror: ~/.config/kitty/vanta.conf (resolved by terminal-sync).

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.background = "dark"
vim.g.colors_name = "vanta"

local p = {
  -- backgrounds / structural greys
  bg = "#0a0a0a", bg1 = "#141414", bg2 = "#1a1a1a", bg3 = "#242424", bg4 = "#2e2e2e",
  line = "#3a3a3a", grey0 = "#4a4a4a", grey1 = "#6a6a6a", grey2 = "#808080",
  grey3 = "#9a9a9a", grey4 = "#a0a0a0", grey5 = "#b0b0b0", grey6 = "#c0c0c0", grey7 = "#c8c8c8",
  fg = "#d8d8d8", fg1 = "#e4e4e4", white = "#f0f0f0",
  -- neon turquoise accent
  teal = "#2ae8c8", teal_lt = "#79f0d8", teal_br = "#a9ffe8",
  teal_bg = "#11463d", teal_bg2 = "#103a33", teal_fg = "#cdf5ec",
  -- diff / git signals
  add = "#7fb07f", add_bg = "#16271b",
  del = "#c46b6b", del_bg = "#271819",
  chg = "#7f9bb8", chg_bg = "#1b2026", chg_txt_bg = "#2a3a4a",
  -- diagnostics
  err = "#c46b6b", warn = "#c2a878", info = "#79f0d8", hint = "#6fb3a6", ok = "#7fb07f",
  none = "NONE",
}

local groups = {
  -- editor UI
  Normal = { fg = p.fg, bg = p.none },
  NormalNC = { fg = p.fg, bg = p.none },
  NormalFloat = { fg = p.fg, bg = p.bg1 },
  FloatBorder = { fg = p.grey1, bg = p.bg1 },
  FloatTitle = { fg = p.teal, bg = p.bg1, bold = true },
  ColorColumn = { bg = p.bg1 },
  Conceal = { fg = p.grey1 },
  Cursor = { fg = p.bg, bg = p.teal },
  lCursor = { fg = p.bg, bg = p.teal },
  CursorIM = { fg = p.bg, bg = p.teal },
  TermCursor = { fg = p.bg, bg = p.teal },
  CursorColumn = { bg = p.bg1 },
  CursorLine = { bg = p.none },
  Directory = { fg = p.teal },
  EndOfBuffer = { fg = p.bg2 },
  ErrorMsg = { fg = p.err },
  WinSeparator = { fg = p.bg4, bg = p.none },
  VertSplit = { fg = p.bg4, bg = p.none },
  Folded = { fg = p.grey2, bg = p.bg1 },
  FoldColumn = { fg = p.grey0, bg = p.none },
  SignColumn = { fg = p.grey2, bg = p.none },
  IncSearch = { fg = p.bg, bg = p.teal_br },
  CurSearch = { fg = p.bg, bg = p.teal_br },
  Substitute = { fg = p.bg, bg = p.del },
  LineNr = { fg = p.grey0 },
  LineNrAbove = { fg = p.grey0 },
  LineNrBelow = { fg = p.grey0 },
  CursorLineNr = { fg = p.teal, bold = true },
  MatchParen = { fg = p.teal_br, bg = p.teal_bg, bold = true },
  ModeMsg = { fg = p.fg },
  MsgArea = { fg = p.fg },
  MoreMsg = { fg = p.teal },
  NonText = { fg = p.bg4 },
  Pmenu = { fg = p.grey6, bg = p.bg2 },
  PmenuSel = { fg = p.teal_fg, bg = p.teal_bg },
  PmenuKind = { fg = p.teal_lt, bg = p.bg2 },
  PmenuKindSel = { fg = p.teal_lt, bg = p.teal_bg },
  PmenuExtra = { fg = p.grey2, bg = p.bg2 },
  PmenuExtraSel = { fg = p.grey6, bg = p.teal_bg },
  PmenuSbar = { bg = p.bg3 },
  PmenuThumb = { bg = p.grey0 },
  Question = { fg = p.teal },
  QuickFixLine = { bg = p.bg2, bold = true },
  Search = { fg = p.bg, bg = p.teal },
  SpecialKey = { fg = p.grey0 },
  SpellBad = { undercurl = true, sp = p.err },
  SpellCap = { undercurl = true, sp = p.warn },
  SpellLocal = { undercurl = true, sp = p.info },
  SpellRare = { undercurl = true, sp = p.hint },
  StatusLine = { fg = p.teal_fg, bg = p.teal_bg2 },
  StatusLineNC = { fg = p.grey1, bg = p.bg1 },
  TabLine = { fg = p.grey2, bg = p.bg1 },
  TabLineFill = { bg = p.bg },
  TabLineSel = { fg = p.teal_fg, bg = p.teal_bg },
  Title = { fg = p.teal, bold = true },
  Visual = { bg = p.teal_bg },
  VisualNOS = { bg = p.teal_bg },
  WarningMsg = { fg = p.warn },
  Whitespace = { fg = p.bg4 },
  WildMenu = { fg = p.bg, bg = p.teal },
  WinBar = { fg = p.fg, bg = p.none },
  WinBarNC = { fg = p.grey1, bg = p.none },

  -- legacy syntax
  Comment = { fg = p.grey2, italic = true },
  Constant = { fg = p.grey6 },
  String = { fg = p.grey6 },
  Character = { fg = p.grey6 },
  Number = { fg = p.grey5 },
  Boolean = { fg = p.grey5 },
  Float = { fg = p.grey5 },
  Identifier = { fg = p.grey4 },
  Function = { fg = p.grey7 },
  Statement = { fg = p.teal },
  Conditional = { fg = p.teal },
  Repeat = { fg = p.teal },
  Label = { fg = p.teal },
  Operator = { fg = p.grey3 },
  Keyword = { fg = p.teal },
  Exception = { fg = p.teal },
  PreProc = { fg = p.teal_lt },
  Include = { fg = p.teal },
  Define = { fg = p.teal_lt },
  Macro = { fg = p.teal_lt },
  PreCondit = { fg = p.teal_lt },
  Type = { fg = p.teal_lt },
  StorageClass = { fg = p.teal_lt },
  Structure = { fg = p.teal_lt },
  Typedef = { fg = p.teal_lt },
  Special = { fg = p.grey5 },
  SpecialChar = { fg = p.grey5 },
  Tag = { fg = p.teal },
  Delimiter = { fg = p.grey3 },
  SpecialComment = { fg = p.grey3 },
  Debug = { fg = p.del },
  Underlined = { fg = p.teal, underline = true },
  Ignore = { fg = p.grey0 },
  Error = { fg = p.err },
  Todo = { fg = p.bg, bg = p.teal, bold = true },

  -- diff (builtin + diff syntax)
  DiffAdd = { bg = p.add_bg },
  DiffChange = { bg = p.chg_bg },
  DiffDelete = { fg = p.del, bg = p.del_bg },
  DiffText = { fg = p.fg1, bg = p.chg_txt_bg },
  diffAdded = { fg = p.add },
  diffRemoved = { fg = p.del },
  diffChanged = { fg = p.chg },
  diffLine = { fg = p.teal },
  diffFile = { fg = p.teal_lt },
  diffNewFile = { fg = p.add },
  diffOldFile = { fg = p.del },
  diffIndexLine = { fg = p.grey2 },
  Added = { fg = p.add },
  Removed = { fg = p.del },
  Changed = { fg = p.chg },

  -- diagnostics
  DiagnosticError = { fg = p.err },
  DiagnosticWarn = { fg = p.warn },
  DiagnosticInfo = { fg = p.info },
  DiagnosticHint = { fg = p.hint },
  DiagnosticOk = { fg = p.ok },
  DiagnosticUnderlineError = { undercurl = true, sp = p.err },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.warn },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.info },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.hint },
  DiagnosticUnderlineOk = { undercurl = true, sp = p.ok },
  DiagnosticVirtualTextError = { fg = p.err, bg = p.del_bg },
  DiagnosticVirtualTextWarn = { fg = p.warn, bg = p.bg1 },
  DiagnosticVirtualTextInfo = { fg = p.info, bg = p.bg1 },
  DiagnosticVirtualTextHint = { fg = p.hint, bg = p.bg1 },

  -- LSP references / inlay
  LspReferenceText = { bg = p.bg3 },
  LspReferenceRead = { bg = p.bg3 },
  LspReferenceWrite = { bg = p.bg3 },
  LspInlayHint = { fg = p.grey1, bg = p.bg1 },
  LspCodeLens = { fg = p.grey1 },
  LspSignatureActiveParameter = { fg = p.teal, bold = true },

  -- treesitter
  ["@comment"] = { link = "Comment" },
  ["@comment.error"] = { fg = p.err },
  ["@comment.warning"] = { fg = p.warn },
  ["@comment.todo"] = { link = "Todo" },
  ["@comment.note"] = { fg = p.info },
  ["@keyword"] = { fg = p.teal },
  ["@keyword.function"] = { fg = p.teal },
  ["@keyword.return"] = { fg = p.teal },
  ["@keyword.operator"] = { fg = p.teal },
  ["@keyword.conditional"] = { fg = p.teal },
  ["@keyword.repeat"] = { fg = p.teal },
  ["@keyword.import"] = { fg = p.teal },
  ["@keyword.exception"] = { fg = p.teal },
  ["@keyword.directive"] = { fg = p.teal_lt },
  ["@conditional"] = { fg = p.teal },
  ["@repeat"] = { fg = p.teal },
  ["@exception"] = { fg = p.teal },
  ["@include"] = { fg = p.teal },
  ["@type"] = { fg = p.teal_lt },
  ["@type.builtin"] = { fg = p.teal_lt },
  ["@type.definition"] = { fg = p.teal_lt },
  ["@type.qualifier"] = { fg = p.teal },
  ["@namespace"] = { fg = p.teal_lt },
  ["@module"] = { fg = p.teal_lt },
  ["@function"] = { fg = p.grey7 },
  ["@function.builtin"] = { fg = p.grey7 },
  ["@function.call"] = { fg = p.grey7 },
  ["@function.macro"] = { fg = p.teal_lt },
  ["@method"] = { fg = p.grey7 },
  ["@method.call"] = { fg = p.grey7 },
  ["@constructor"] = { fg = p.teal_lt },
  ["@variable"] = { fg = p.fg },
  ["@variable.builtin"] = { fg = p.grey4 },
  ["@variable.parameter"] = { fg = p.grey5 },
  ["@variable.member"] = { fg = p.grey5 },
  ["@parameter"] = { fg = p.grey5 },
  ["@field"] = { fg = p.grey5 },
  ["@property"] = { fg = p.grey5 },
  ["@constant"] = { fg = p.grey5 },
  ["@constant.builtin"] = { fg = p.grey5 },
  ["@constant.macro"] = { fg = p.teal_lt },
  ["@string"] = { fg = p.grey6 },
  ["@string.regex"] = { fg = p.grey5 },
  ["@string.escape"] = { fg = p.teal_lt },
  ["@string.special"] = { fg = p.teal_lt },
  ["@character"] = { fg = p.grey6 },
  ["@character.special"] = { fg = p.teal_lt },
  ["@number"] = { fg = p.grey5 },
  ["@boolean"] = { fg = p.grey5 },
  ["@float"] = { fg = p.grey5 },
  ["@operator"] = { fg = p.grey3 },
  ["@punctuation.delimiter"] = { fg = p.grey2 },
  ["@punctuation.bracket"] = { fg = p.grey2 },
  ["@punctuation.special"] = { fg = p.teal },
  ["@tag"] = { fg = p.teal },
  ["@tag.attribute"] = { fg = p.grey5 },
  ["@tag.delimiter"] = { fg = p.grey2 },
  ["@label"] = { fg = p.teal },
  ["@annotation"] = { fg = p.teal_lt },
  ["@attribute"] = { fg = p.teal_lt },
  ["@markup.heading"] = { fg = p.teal, bold = true },
  ["@markup.heading.1"] = { fg = p.teal, bold = true },
  ["@markup.heading.2"] = { fg = p.teal_lt, bold = true },
  ["@markup.heading.3"] = { fg = p.grey7, bold = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.link"] = { fg = p.teal, underline = true },
  ["@markup.link.url"] = { fg = p.teal_lt, underline = true },
  ["@markup.raw"] = { fg = p.grey6 },
  ["@markup.list"] = { fg = p.teal },
  ["@markup.quote"] = { fg = p.grey2, italic = true },
  ["@diff.plus"] = { fg = p.add },
  ["@diff.minus"] = { fg = p.del },
  ["@diff.delta"] = { fg = p.chg },

  -- LSP semantic tokens
  ["@lsp.type.class"] = { link = "@type" },
  ["@lsp.type.decorator"] = { fg = p.teal_lt },
  ["@lsp.type.enum"] = { link = "@type" },
  ["@lsp.type.enumMember"] = { fg = p.grey5 },
  ["@lsp.type.function"] = { link = "@function" },
  ["@lsp.type.interface"] = { link = "@type" },
  ["@lsp.type.macro"] = { fg = p.teal_lt },
  ["@lsp.type.method"] = { link = "@function" },
  ["@lsp.type.namespace"] = { link = "@namespace" },
  ["@lsp.type.parameter"] = { fg = p.grey5 },
  ["@lsp.type.property"] = { fg = p.grey5 },
  ["@lsp.type.struct"] = { link = "@type" },
  ["@lsp.type.type"] = { link = "@type" },
  ["@lsp.type.variable"] = { link = "@variable" },
  ["@lsp.type.keyword"] = { fg = p.teal },

  -- gitsigns
  GitSignsAdd = { fg = p.add },
  GitSignsChange = { fg = p.chg },
  GitSignsDelete = { fg = p.del },
  GitSignsAddNr = { fg = p.add },
  GitSignsChangeNr = { fg = p.chg },
  GitSignsDeleteNr = { fg = p.del },
  GitSignsAddLn = { bg = p.add_bg },
  GitSignsChangeLn = { bg = p.chg_bg },
  GitSignsDeleteLn = { bg = p.del_bg },
  GitSignsCurrentLineBlame = { fg = p.grey1, italic = true },

  -- blink.cmp
  BlinkCmpMenu = { fg = p.grey6, bg = p.bg2 },
  BlinkCmpMenuBorder = { fg = p.grey1, bg = p.bg2 },
  BlinkCmpMenuSelection = { fg = p.teal_fg, bg = p.teal_bg },
  BlinkCmpScrollBarThumb = { bg = p.grey0 },
  BlinkCmpScrollBarGutter = { bg = p.bg3 },
  BlinkCmpLabel = { fg = p.grey6 },
  BlinkCmpLabelDeprecated = { fg = p.grey1, strikethrough = true },
  BlinkCmpLabelMatch = { fg = p.teal, bold = true },
  BlinkCmpKind = { fg = p.teal_lt },
  BlinkCmpDoc = { fg = p.fg, bg = p.bg1 },
  BlinkCmpDocBorder = { fg = p.grey1, bg = p.bg1 },
  BlinkCmpDocSeparator = { fg = p.bg4 },
  BlinkCmpSignatureHelp = { fg = p.fg, bg = p.bg1 },
  BlinkCmpSignatureHelpBorder = { fg = p.grey1, bg = p.bg1 },
  BlinkCmpGhostText = { fg = p.grey1, italic = true },

  -- telescope
  TelescopeNormal = { fg = p.fg, bg = p.bg1 },
  TelescopeBorder = { fg = p.grey1, bg = p.bg1 },
  TelescopePromptNormal = { fg = p.fg, bg = p.bg2 },
  TelescopePromptBorder = { fg = p.grey1, bg = p.bg2 },
  TelescopePromptTitle = { fg = p.bg, bg = p.teal, bold = true },
  TelescopeResultsTitle = { fg = p.bg, bg = p.teal, bold = true },
  TelescopePreviewTitle = { fg = p.bg, bg = p.add, bold = true },
  TelescopePromptPrefix = { fg = p.teal },
  TelescopeSelection = { fg = p.fg1, bg = p.teal_bg },
  TelescopeSelectionCaret = { fg = p.teal, bg = p.teal_bg },
  TelescopeMatching = { fg = p.teal, bold = true },
  TelescopeMultiSelection = { fg = p.teal_lt },

  -- neo-tree
  NeoTreeNormal = { fg = p.fg, bg = p.none },
  NeoTreeNormalNC = { fg = p.fg, bg = p.none },
  NeoTreeDirectoryName = { fg = p.fg },
  NeoTreeDirectoryIcon = { fg = p.teal },
  NeoTreeRootName = { fg = p.teal, bold = true },
  NeoTreeFileName = { fg = p.grey6 },
  NeoTreeGitAdded = { fg = p.add },
  NeoTreeGitModified = { fg = p.chg },
  NeoTreeGitDeleted = { fg = p.del },
  NeoTreeGitUntracked = { fg = p.teal_lt },
  NeoTreeIndentMarker = { fg = p.bg4 },
  NeoTreeExpander = { fg = p.grey2 },

  -- bufferline (key groups; rest derives)
  BufferLineFill = { bg = p.bg },
  BufferLineBackground = { fg = p.grey1, bg = p.bg1 },
  BufferLineBufferVisible = { fg = p.grey2, bg = p.bg1 },
  BufferLineBufferSelected = { fg = p.teal_fg, bg = p.none, bold = true },
  BufferLineSeparator = { fg = p.bg, bg = p.bg1 },
  BufferLineSeparatorVisible = { fg = p.bg, bg = p.bg1 },
  BufferLineSeparatorSelected = { fg = p.bg, bg = p.none },
  BufferLineIndicatorSelected = { fg = p.teal, bg = p.none },
  BufferLineModified = { fg = p.add, bg = p.bg1 },
  BufferLineModifiedSelected = { fg = p.add, bg = p.none },
  BufferLineModifiedVisible = { fg = p.add, bg = p.bg1 },

  -- which-key
  WhichKey = { fg = p.teal },
  WhichKeyGroup = { fg = p.teal_lt },
  WhichKeyDesc = { fg = p.fg },
  WhichKeySeparator = { fg = p.grey2 },
  WhichKeyFloat = { bg = p.bg1 },
  WhichKeyBorder = { fg = p.grey1, bg = p.bg1 },
  WhichKeyValue = { fg = p.grey2 },

  -- indent guides (ibl + snacks)
  IblIndent = { fg = p.bg3 },
  IblScope = { fg = p.grey0 },
  SnacksIndent = { fg = p.bg3 },
  SnacksIndentScope = { fg = p.grey0 },
}

for group, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, group, spec)
end
