# Colors (Dark plus)
[colors.primary]
background = '0x1E1E1E'
foreground = '0xD4D4D4'

[colors.normal]
black =   '0x1E1E1E'
red =     '0xF44747'
green =   '0x608B4E'
yellow =  '0xD7BA7D'
blue =    '0x569CD6'
magenta = '0xC586C0'
cyan =    '0x9CDCFE'
white =   '0xD4D4D4'

[colors.bright]
black =   '0x3C3C3C'   # A lighter shade of black
red =     '0xF77F7F'   # A lighter, more vibrant red
green =   '0x80A090'   # A lighter, more vibrant green
yellow =  '0xE2C68F'   # A lighter, more vibrant yellow
blue =    '0x6A9EC9'   # A lighter, more vibrant blue
magenta = '0xD6A5D1'   # A lighter, more vibrant magenta
cyan =    '0xA0D6FF'   # A lighter, more vibrant cyan
white =   '0xE4E4E4'   # A lighter shade of white (not much lighter needed)
